Update #119
NeighborhoodInfoDC/RealProp pull request #121
Opened 2022-06-24 14:46 UTC by rpitingolo

Can you give these edits a review, please?

2022-06-24 20:51 UTC, lhendey requested changes

2022-06-24 20:51 UTC, lhendey commented on Prog/Ownerpt/Create_new_ownerpt.sas
> + Modifications: 06/24/22 - Reworked the program to use new CAMA sales file.
Rob - it would be helpful to be a little more detailed here and note that the Cama_property_sales replaced the itspe_property_sales which no longer exists.

2022-06-24 20:51 UTC, lhendey commented on Prog/Ownerpt/Create_new_ownerpt.sas
> +data Cama_property_sales_nd;
Rob was the read_itspe_files a separate step before? can't batch submit this program if it's using temp files.

2022-06-24 20:51 UTC, lhendey commented on Prog/Ownerpt/Read_itspe_files.sas
> +		informat PROPTYPE $99.;
the field PROPTYPE in the ownerpt file looks like its getting cut off

2022-06-24 20:51 UTC, lhendey commented on Prog/Ownerpt/Read_itspe_files.sas
> +		informat DUEDATE1 best32.;
do we normally reformat these dates? shouldn't be numbers should they? show up like 6012022

2022-06-27 15:38 UTC, rpitingolo commented on Prog/Ownerpt/Create_new_ownerpt.sas
> + Modifications: 06/24/22 - Reworked the program to use new CAMA sales file.
Sure

2022-06-27 15:58 UTC, rpitingolo commented on Prog/Ownerpt/Read_itspe_files.sas
> +		informat PROPTYPE $99.;
It's truncated on the raw data. Not sure we can do anything about that other than deal with it in a future step.

2022-06-27 16:01 UTC, rpitingolo commented on Prog/Ownerpt/Read_itspe_files.sas
> +		informat DUEDATE1 best32.;
Which dates are you asking about specifically? Most of the dates are read-in as character and then reformatted as numeric sasdates lower in the data step.

2022-06-27 16:03 UTC, rpitingolo commented on Prog/Ownerpt/Read_itspe_files.sas
> +		informat DUEDATE1 best32.;
Oh I see it's the due dates. I'll fix those.

2022-06-27 16:57 UTC, merged