New process for creating parcel_geo
NeighborhoodInfoDC/RealProp pull request #127
Opened 2022-07-11 21:41 UTC by rpitingolo

@lhendey can you review, please? I crated a new macro %Parcel_geo_update_mar which creates parcel_geo. This uses the MAR address points and SSL xref file to match to the SSLs on parcel_base. For those SSLs that don't match they are geocoded using the MAR geocode macro. This lets us get the new 2020 census geographies and Ward 2022 on the parcel_geo file.

2022-07-13 19:47 UTC, lhendey requested changes
@rpitingolo getting errors trying to run this.

2022-07-13 19:47 UTC, lhendey commented on Macros/Parcel_geo_update_mar.sas
> +	by ssl;
Rob - getting multiple lengths on the SSL on this merge - i'd like to address that since it's a char var and we want to keep that consistent.

2022-07-13 19:47 UTC, lhendey commented on Macros/Parcel_geo_update_mar.sas
> +		Parcels_geocoded (in=b)
so getting erro that parcels_geocoded doesn't exist.

2022-07-20 15:56 UTC, rpitingolo commented
@lhendey turning back to this now that the maps are done. Is this ready to finalize now that the MAR dataset has the SSL variable corrected?

2022-07-21 16:21 UTC, lhendey approved these changes

2022-07-21 17:28 UTC, merged